draw_self();
draw_text(x, y + 100, "State: " + string(state));
draw_text(x, y + 120, "Direction: " + string(characterDirection));
draw_text(x, y + 140, "Jumping: " + string(isJumping));
draw_text(x, y + 160, "Dashing: " + string(isDashing));
draw_text(x, y + 180, "Dash Jump: " + string(dashJump));
draw_text(x, y + 200, "Sprite Index: " + string(sprite_index));
draw_text(x, y + 220, "Sprite Image Index: " + string(floor(image_index)));
draw_text(x, y + 240, "Blocking: " + string(isBlocking));
draw_text(x, y + 260, "Attacking: " + string(isAttacking));
draw_text(x, y + 280, "Attack Animation: " + string(attackAnimation));
draw_text(x, y - 100, "X Position: " + string(x));
draw_text(x, y - 120, "Y Position: " + string(y));
